version: "3"

services:
  matrix-e2ee-webhook:
    build: .
    image: matrix-e2ee-webhook:master
    container_name: matrix-e2ee-webhook
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
